In [1]:
from google.colab import drive
import pandas as pd
drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [4]:
mlb = pd.read_excel('/content/gdrive/My Drive/MLB.xlsx')

In [6]:
df = mlb.copy()
df

Year              Champion  Wins  Losses  Ties  WinRatio
0    1903      Boston Americans    91      47     3     0.656
1    1905       New York Giants   105      48     2     0.684
2    1906     Chicago White Sox    93      58     3     0.614
3    1907          Chicago Cubs   107      45     3     0.700
4    1908          Chicago Cubs    99      55     4     0.639
..    ...                   ...   ...     ...   ...       ...
107  2012  San Francisco Giants    94      68     0     0.580
108  2013        Boston Red Sox    97      65     0     0.599
109  2014  San Francisco Giants    88      74     0     0.543
110  2015    Kansas City Royals    95      67     0     0.586
111  2016          Chicago Cubs   103      58     1     0.639

[112 rows x 6 columns]

In [7]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Year      112 non-null    int64  
 1   Champion  112 non-null    object 
 2   Wins      112 non-null    int64  
 3   Losses    112 non-null    int64  
 4   Ties      112 non-null    int64  
 5   WinRatio  112 non-null    float64
dtypes: float64(1), int64(4), object(1)
memory usage: 5.4+ KB


In [8]:
# # 연습)
# 1.구단 이름
# 2. 우승팀들의 평균 승률
# 3. 100승 이상인 팀
# 4. 양키스의 평균승률
# 5. 양키즈가 처음 우승한연도, 마지막우승 연도
# 6.최다우승top5
# 7.월드시리즈가 안열리는연도

In [42]:
#1) 구단이름
df['Champion'].value_counts().index

Index(['New York Yankees', 'St. Louis Cardinals', 'Boston Red Sox',
       'Los Angeles Dodgers', 'Philadelphia Athletics', 'New York Giants',
       'Cincinatti Reds', 'Pittsburgh Pirates', 'Oakland Athletics',
       'Detroit Tigers', 'Baltimore Orioles', 'San Francisco Giants',
       'Chicago Cubs', 'Chicago White Sox', 'Toronto Blue Jays',
       'Florida Marlins', 'Cleveland Indians', 'New York Mets',
       'Philadelphia Phillies', 'Kansas City Royals', 'Minnesota Twins',
       'Arizona Diamondbacks', 'Atlanta Braves', 'Anaheim Angels',
       'Boston Americans', 'Milwaukee Braves', 'Washington Senators',
       'Boston Braves', 'Pittsburg Pirates', 'Brooklyn Dodgers'],
      dtype='object')

In [43]:
# 2. 우승팀들의 평균 승률
# df.groupby('Champion',as_index=False).agg(n = ('WinRatio','mean'))
df.pivot_table(values='WinRatio',index="Champion",aggfunc='mean')

WinRatio
Champion                        
Anaheim Angels          0.611000
Arizona Diamondbacks    0.568000
Atlanta Braves          0.625000
Baltimore Orioles       0.626000
Boston Americans        0.656000
Boston Braves           0.611000
Boston Red Sox          0.607714
Brooklyn Dodgers        0.640000
Chicago Cubs            0.659333
Chicago White Sox       0.624000
Cincinatti Reds         0.639400
Cleveland Indians       0.630500
Detroit Tigers          0.616750
Florida Marlins         0.565000
Kansas City Royals      0.574000
Los Angeles Dodgers     0.585800
Milwaukee Braves        0.616000
Minnesota Twins         0.555500
New York Giants         0.625400
New York Mets           0.642000
New York Yankees        0.638630
Oakland Athletics       0.586750
Philadelphia Athletics  0.664600
Philadelphia Phillies   0.565000
Pittsburg Pirates       0.721000
Pittsburgh Pirates      0.610250
San Francisco Giants    0.563667
St. Louis Cardinals     0.607818
Toronto Blue Jays       0.589500
Washington Senators     0.596000

In [44]:
# 3. 100승 이상인 팀
# set(df.query('Wins>=100')['Champion'])
df[df['Wins']>=100]['Champion'].unique()

array(['New York Giants', 'Chicago Cubs', 'Pittsburg Pirates',
       'Philadelphia Athletics', 'Boston Red Sox', 'Chicago White Sox',
       'New York Yankees', 'St. Louis Cardinals', 'Cincinatti Reds',
       'Detroit Tigers', 'New York Mets', 'Baltimore Orioles'],
      dtype=object)

In [50]:
# 4. 양키스의 평균승률
# df.query('Champion=="New York Yankees"').groupby('Champion',as_index=False).agg(mean=('WinRatio','mean'))
nyy =df.query('Champion=="New York Yankees"')
nyy['WinRatio'].mean()

0.6386296296296295

In [54]:
# 5. 양키즈가 처음 우승한연도, 마지막우승 연도
# df.query('Champion=="New York Yankees"').sort_values('Year').head(1)['Year']
# nyy.iloc[0]['Year']
# df.query('Champion=="New York Yankees"').sort_values('Year').tail(1)
nyy.iloc[-1]['Year']

2009

In [66]:
# 6.최다우승top5
# df.groupby('Champion',as_index=False).agg(cnt=('Champion','count')).sort_values('cnt',ascending=False).head()
top_teams = df.groupby('Champion').size().sort_values(ascending=False)
top_teams
# 근데 이건 공정한가? 5등까지인디 동점인애들이 더 있으면 걔들도 5등인디..

Champion
New York Yankees          27
St. Louis Cardinals       11
Boston Red Sox             7
Los Angeles Dodgers        5
Cincinatti Reds            5
New York Giants            5
Philadelphia Athletics     5
Detroit Tigers             4
Oakland Athletics          4
Pittsburgh Pirates         4
Chicago White Sox          3
Chicago Cubs               3
San Francisco Giants       3
Baltimore Orioles          3
Florida Marlins            2
Kansas City Royals         2
Philadelphia Phillies      2
Minnesota Twins            2
New York Mets              2
Toronto Blue Jays          2
Cleveland Indians          2
Pittsburg Pirates          1
Anaheim Angels             1
Milwaukee Braves           1
Arizona Diamondbacks       1
Brooklyn Dodgers           1
Boston Braves              1
Boston Americans           1
Atlanta Braves             1
Washington Senators        1
dtype: int64

In [67]:
n = top_teams[4]
n
top5 = top_teams[top_teams>=n]
top5

Champion
New York Yankees          27
St. Louis Cardinals       11
Boston Red Sox             7
Los Angeles Dodgers        5
Cincinatti Reds            5
New York Giants            5
Philadelphia Athletics     5
dtype: int64

In [73]:
type(df.groupby('Champion',as_index=False).agg(cnt=('Champion','count')).sort_values('cnt',ascending=False))

pandas.core.frame.DataFrame

In [72]:
type(df.groupby('Champion').size().sort_values(ascending=False))

pandas.core.series.Series

In [23]:
# 7.월드시리즈가 안열리는연도
df['Year']

0      1903
1      1905
2      1906
3      1907
4      1908
       ... 
107    2012
108    2013
109    2014
110    2015
111    2016
Name: Year, Length: 112, dtype: int64

In [ ]:
game_years = df['Year'].tolist()
game_years

In [ ]:
list = list(range(1903,2017))
list

In [30]:
set(list) - set(game_years)

{1904, 1994}

In [34]:
len(list)

114

In [35]:
len(game_years)

112

In [74]:
import numpy as np

In [75]:
# np에는 두 배열의 차이를 알려주는 함수가 있다
# np.setdiff1d(list1,list2)
np.setdiff1d(list,game_years)

array([1904, 1994])

In [78]:
# np.setdiff1d 를 알아보자
a = np.arange(10)
b = np.arange(5)

In [79]:
np.setdiff1d(a,b)

array([5, 6, 7, 8, 9])

In [83]:
start = df.iloc[0]['Year']
end = df.iloc[-1]['Year']
all_years = np.arange(start,end+1)
all_years

array([1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913,
       1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924,
       1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935,
       1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946,
       1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957,
       1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968,
       1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979,
       1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016])

In [87]:
years = df['Year'].values
type(years)

numpy.ndarray

In [86]:
np.setdiff1d(all_years,years)

array([1904, 1994])